server:
  # 服务端口号
  port: 8180
spring:
  output:
    ansi:
      enabled: DETECT
  http:
    encoding:
      charset: UTF-8
    multipart:
      maxFileSize: -1
      maxRequestSize: 100MB
  datasource:
    # MYSQL数据库驱动
    driver-class-name: com.mysql.jdbc.Driver
    # 数据库地址
    url: jdbc:mysql://localhost:3306/bhdemos?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true&createDatabaseIfNotExist=true
    # 数据库用户名
    username: root
    # 数据库密码
    password: root
  jpa:
    database: MYSQL
    # 开发时显示sql，部署到生产环境时设为false
    show-sql: false
    # 使用mysql方言
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      # 下面两个配置对应hibernate的属性
      ddl-auto: update
    properties:
      hibernate:
        # 格式化sql 语句
        format_sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: test
    password: test
  redis:
    # redis数据库索引（默认为0），我们使用索引为3的数据库，避免和其他数据库冲突
    database: 9
    # redis服务器地址（默认为localhost）
    host: localhost
    # redis端口（默认为6379）
    port: 6379
    # redis访问密码（默认为空）
    password: 
    # redis连接超时时间（单位为毫秒）
    timeout: 3600000
    # redis连接池配置
    jedis:
      pool:
        # 最大可用连接数（默认为8，负数表示无限）
        max-active: -1
        # 最大空闲连接数（默认为8，负数表示无限）
        max-idle: 200
        # 最小空闲连接数（默认为0，该值只有为正数才有作用）
        min-idle: 0
        # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
        max-wait: -1
      
# LOGGING
logging:
  level:
    root: info