server:
  # 服务端口号
  port: 8080
spring:
  datasource:
    # MYSQL数据库驱动
    driver-class-name: com.mysql.jdbc.Driver
    # 数据库地址
    url: jdbc:mysql://localhost:3306/bhdemos?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true&createDatabaseIfNotExist=true
    # 数据库用户名
    username: root
    # 数据库密码
    password: root
  jpa:
    database: default
    # 开发时显示sql，部署到生产环境时设为false
    show-sql: true
    # 使用mysql方言
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      # 下面两个配置对应hibernate的属性
      ddl-auto: update
    properties:
      hibernate:
        # 格式化sql 语句
        format_sql: true
      
# LOGGING
logging:
  level:
    root: info
    